name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: nuget restore ./WindowsFormsApp1.sln

    - name: Build solution
      run: msbuild ./WindowsFormsApp1.sln /p:Configuration=Release

    # Agrega pruebas si tienes proyecto de tests compatible con .NET Framework

